name: running test, build image, push registry, deploy
on:
  push:
    branches: [ main ]
jobs:
  running-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Run test
        run: go test -v ./... -cover
      - run: go version

  buildimage:
    name: Build image
    runs-on: ubuntu-latest
    needs: running-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Environment
        run: |
          echo "ENV_PROJECT=${{ secrets.ENV_PROJECT }}" > .env
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
          echo "DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}" >> .env
      - name: Display contents of .env file
        run: cat .env
      - name: Build Docker image
        run: |
          docker build -t mifthahuddin/forestcontainer:1.0 . \
            --build-arg ENV_PROJECT="${{ secrets.ENV_PROJECT }}" \
            --build-arg DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" \
            --build-arg DOCKERHUB_PASSWORD="${{ secrets.DOCKERHUB_PASSWORD }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Docker image
        run: docker push mifthahuddin/forestcontainer:1.0
