name: running test, build image, push registry, deploy
on:
  push:
    branches: [ main ]
jobs:
  running-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.0'

      - name: Run tests
        run: go test -v ./... -cover

      - name: Check Go version
        run: go version

  buildimage:
    name: Build Image
    runs-on: ubuntu-latest
    needs: running-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Environment
        run: echo "REGISTRY=${{ secrets.ENV_PROJECT }}" >> .env

      - name: Build Docker image
        run: |
          docker build -t mifthahuddin/forestcontainer:1.0 .
          docker push mifthahuddin/forestcontainer:1.0

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: buildimage
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/Forest-API
            docker pull mifthahuddin/forestcontainer:1.0
            docker run -d -p 8000:8000 -e REGISTRY=${{ secrets.ENV_PROJECT }} mifthahuddin/forestcontainer:1.0
